class_name PlayerAnimations extends Resource

const idle:String = "idle"
const walk:String = "walk"
const run:String = "run"
const jumpUp:String = "jumpUp"
const jumpTop:String = "jumpTop"
const jumpDown:String = "jumpDown"
const airSpin:String = "airSpin"
const land:String = "land"
const idleCrouch:String = "idleCrouch"
const walkCrouch:String = "walkCrouch"
const wallLand:String = "wallLand"
const climbLedge:String = "climbLedge"
const wallSlide:String = "wallSlide"
